[package]
name = "mysql_01"
version = "0.1.0"
authors = ["maheensaleh <salehmaheen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysql = "16.1.0"
